# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

continuous_rle_impl <- function(x, c) {
    .Call(`_mists_continuous_rle_impl`, x, c)
}

