# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

na_rle_cpp <- function(x) {
    .Call(`_mists_na_rle_cpp`, x)
}

continuous_rle_impl <- function(x) {
    .Call(`_mists_continuous_rle_impl`, x)
}

